ktor:
    application:
        modules:
            - com.moashrafff.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  issuer: "https://0.0.0.0:8080/"
  realm: "ktor sample app"
  claimField: "id"

database:
  url: "jdbc:mysql://localhost:3306/ktor_showcase_db"
  driver: "com.mysql.cj.jdbc.Driver"
  user: "ktor_moashrafff_db_user"
